[annotate]
advanced_size = "0"
color_arrow = "1,1,1,1"
color_blur = "0.96,0.2,0.28,1"
color_brush = "0.96,0.2,0.28,1"
color_circle = "0.96,0.2,0.28,1"
color_crop = "0.96,0.2,0.28,1"
color_eraser = "0.96,0.2,0.28,1"
color_highlighter = "1,0.91,0.2,1"
color_line = "0.2,0.55,1,1"
color_move = "0.96,0.2,0.28,1"
color_numbering = "0.96,0.2,0.28,1"
color_rectangle = "1,1,1,1"
color_text = "1,1,1,1"
fill = "0"
tool = "text"
toolbar_positions = "{\"eDP-1\":{\"x\":420.16796875,\"y\":1139.796875}}"
width_arrow = "6"
width_blur = "32"
width_brush = "6"
width_circle = "6"
width_crop = "6"
width_eraser = "28"
width_highlighter = "24"
width_line = "6"
width_move = "6"
width_numbering = "32"
width_rectangle = "6"
width_text = "24"

[security_migrations]
calendar_credentials_v1 = true

[theme_templates]
applied_builtin_ids = "alacritty btop cava emacs foot gtk3 gtk4 helix hyprland kcolorscheme kitty qt starship"

[wallpaper_panel]
flatten = true