# Theming
include ~/.local/state/quickshell/user/generated/terminal/kitty-theme.conf

# Font
font_family      JetBrains Mono Nerd Font
font_size 14.0

# Set up powerline to always be vissible .
tab_bar_edge top
tab_bar_style powerline
tab_bar_min_tabs 1

# Cursor
cursor_shape beam
cursor_trail 1

# Padding (why weird value? consistency with foot)
single_window_margin_width 21.75
window_margin_width 0

# Set the separation line to a minimal 1-pixel thickness
window_border_width 1px
draw_minimal_borders yes

# No stupid close confirmation
confirm_os_window_close 0
remember_window_size no

# Hide mouse while typing
mouse_hide_wait -3
# Use fish shell
shell fish


# use this layout 
enabled_layouts splits, stack



# ======================= customise kitty keybindings =======================================================================
# Copy
map ctrl+c copy_or_interrupt

# Search
map ctrl+f launch --location=hsplit --allow-remote-control kitty +kitten search.py @active-kitty-window-id

# Scroll & Zoom
map page_up    scroll_page_up
map page_down    scroll_page_down

map ctrl+plus change_font_size all +1
map ctrl+equal change_font_size all +1

# Windows and Controls
map alt+enter new_tab
# Cycle to the next tab
map alt+n next_tab
# Cycle to the previous tab
map alt+p previous_tab

# Open new splits in the current directory using the current layout
map alt+h launch --cwd=current --location=hsplit
map alt+v launch --cwd=current --location=vsplit

# Navigate between split panes using Alt + Arrow keys
map alt+left neighboring_window left
map alt+right neighboring_window right
map alt+up neighboring_window up
map alt+down neighboring_window down


# Close the active split pane
map alt+c close_window

# Close the active tab
map alt+q close_tab

# Resize split panes using Ctrl + Alt + Arrow keys
map ctrl+alt+left resize_window narrower 3
map ctrl+alt+right resize_window wider 3
map ctrl+alt+up resize_window taller 3
map ctrl+alt+down resize_window shorter 3


# Rename the active tab
map alt+r set_tab_title
# Toggle maximizing the current split pane to full screen
map alt+f toggle_layout stack

# Jump directly to a pane by visual letter hints
map alt+k focus_visible_window

include themes/noctalia.conf
